name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23.3.0'

      - name: Install Dependencies
        run: npm ci

      - name: Build Backend
        run: npm run backend:build

      - name: Add Build Artifact
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add dist -f
          git commit -m "Added build artifact"

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: 'ideal-enigma-backend'
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
