name: Deploy Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23.3.0'

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

      #      - name: Add Build Artifact
      #        run: |
      #          cp -R apps/frontend/public dist/apps/frontend/public
      #          git config user.email "actions@github.com"
      #          git config user.name "GitHub Actions"
      #          git add dist -f
      #          git commit -m "Added build artifact"

      - name: Deploy Backend
        uses: akhileshns/heroku-deploy@v3.14.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: 'ideal-enigma-backend'
          heroku_email: ${{ secrets.HEROKU_EMAIL }}

      - name: Deploy Frontend
        uses: akhileshns/heroku-deploy@v3.14.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: 'ideal-enigma-frontend'
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
